In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

In [12]:
A = np.zeros((4, 4))
for i in range(3):
    for j in range(4):
        num = float(input("Camera Parameter의 {}행 {}열의 값을 입력하시오.".format(i+1, j+1)))
        A[i][j] = num

A[3][3]=1

#A = np.matrix(A)

print(A)

B = np.zeros((4, 4))

X = float(input("Base to TCP Px값을 입력하시오."))
Y = float(input("Base to TCP Py값을 입력하시오."))
Z = float(input("Base ti TCP Pz값을 입력하시오."))

R = input("각도는 라디안 값입니까? Y/N")

if((R == "Y") or (R == "y")):
    yaw = float(input("Robot Parameter의 Rx(yaw)값을 입력하시오."))
    pitch = float(input("Robot Parameter의 Ry(pitch)값을 입력하시오."))
    roll = float(input("Robot Parameter의 Rz(Roll)값을 입력하시오."))
    
    yaw = math.degrees(yaw)
    pitch = math.degrees(pitch)
    roll = math.degrees(roll)

else:
    yaw = float(input("Robot Parameter의 Rx(yaw)값을 입력하시오."))
    pitch = float(input("Robot Parameter의 Ry(pitch)값을 입력하시오."))
    roll = float(input("Robot Parameter의 Rz(Roll)값을 입력하시오."))

B[0][0] = math.cos(roll)*math.cos(pitch)
B[0][1] = math.cos(roll)*math.sin(pitch)*math.sin(yaw) - math.sin(roll)*math.cos(yaw)
B[0][2] = math.cos(roll)*math.sin(pitch)*math.cos(yaw) + math.sin(roll)*math.sin(yaw)
B[1][0] = math.sin(roll)*math.cos(pitch)
B[1][1] = math.sin(roll)*math.sin(pitch)*math.sin(yaw) + math.cos(roll)*math.sin(yaw)
B[1][2] = math.sin(roll)*math.sin(pitch)*math.cos(yaw) - math.cos(roll)*math.sin(yaw)
B[2][0] = -math.sin(pitch)
B[2][1] = -math.cos(pitch)*math.sin(yaw)
B[2][2] = math.cos(pitch)*math.cos(yaw)

B[0][3] = X
B[1][3] = Y
B[2][3] = Z
B[3][3] = 1

#B = np.matrix(B)

print(B)

Camera Parameter의 1행 1열의 값을 입력하시오.1
Camera Parameter의 1행 2열의 값을 입력하시오.2
Camera Parameter의 1행 3열의 값을 입력하시오.3
Camera Parameter의 1행 4열의 값을 입력하시오.4
Camera Parameter의 2행 1열의 값을 입력하시오.5
Camera Parameter의 2행 2열의 값을 입력하시오.6
Camera Parameter의 2행 3열의 값을 입력하시오.7
Camera Parameter의 2행 4열의 값을 입력하시오.8
Camera Parameter의 3행 1열의 값을 입력하시오.9
Camera Parameter의 3행 2열의 값을 입력하시오.10
Camera Parameter의 3행 3열의 값을 입력하시오.11
Camera Parameter의 3행 4열의 값을 입력하시오.12
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [ 0.  0.  0.  1.]]
Base to TCP Px값을 입력하시오.1
Base to TCP Py값을 입력하시오.2
Base ti TCP Pz값을 입력하시오.3
각도는 라디안 값입니까? Y/N4
Robot Parameter의 Rx(yaw)값을 입력하시오.5
Robot Parameter의 Ry(pitch)값을 입력하시오.6
Robot Parameter의 Rz(Roll)값을 입력하시오.7
[[ 0.72387454  0.01563704 -0.6897544   1.        ]
 [ 0.63081901 -0.5469033   0.67086267  2.        ]
 [ 0.2794155   0.9207306   0.272364    3.        ]
 [ 0.          0.          0.          1.        ]]


In [16]:
D = np.zeros((12, 12))

D[0][0] = A[0][0] - B[0][0]
D[0][1] = -B[1][0]
D[0][2] = -B[2][0]
D[0][3] = -B[3][0]
D[0][4] = A[0][1]
D[0][8] = A[0][2]

D[1][0] = -B[0][1]
D[1][1] = A[0][0] - B[1][1]
D[1][2] = -B[2][1]
D[1][3] = -B[3][1]
D[1][5] = A[0][1]
D[1][9] = A[0][2]

D[2][0] = -B[0][2]
D[2][1] = -B[1][2]
D[2][2] = A[0][0] - B[2][2]
D[2][3] = A[0][0] - B[3][3]
D[2][6] = A[0][1]
D[2][10]= A[0][2]

D[3][0] = -B[0][3]
D[3][1] = -B[1][3]
D[3][2] = -B[2][3]
D[3][3] = A[0][0] - B[3][3]
D[3][7] = A[0][1]
D[3][11] = A[0][2]

D[4][0] = A[1][0]
D[4][4] = A[1][1] - B[0][0]
D[4][5] = -B[1][0]
D[4][6] = -B[2][0]
D[4][7] = -B[3][0]
D[4][8] = A[1][2]

D[5][1] = A[1][0]
D[5][4] = -B[0][1]
D[5][5] = A[1][1] - B[1][1]
D[5][6] = -B[2][1]
D[5][7] = -B[3][1]
D[5][9] = A[1][2]

D[6][2] = A[1][0]
D[6][4] = -B[0][2]
D[6][5] = -B[1][2]
D[6][6] = A[1][1] - B[2][2]
D[6][7] = -B[3][2]
D[6][10] = A[1][2]

D[7][3] = A[1][0]
D[7][4] = -B[0][3]
D[7][5] = -B[1][3]
D[7][6] = -B[2][3]
D[7][7] = A[1][1] - B[3][3]
D[7][11] = A[1][2]

D[8][0] = A[2][0]
D[8][4] = A[2][1]
D[8][8] = A[2][2] - B[0][0]
D[8][9] = -B[1][0]
D[8][10] = -B[2][0]
D[8][11] = -B[3][0]

D[9][1] = A[2][0]
D[9][5] = A[2][1]
D[9][8] = -B[0][1]
D[9][9] = A[2][2] - B[1][1]
D[9][10] = -B[2][1]
D[9][11] = -B[3][1]

D[10][2] = A[2][0]
D[10][6] = A[2][1]
D[10][8] = -B[0][2]
D[10][9] = -B[1][2]
D[10][10] = A[0][0] - B[2][2]
D[10][11] = -B[3][2]

D[11][3] = A[2][0]
D[11][7] = A[2][1]
D[11][8] = -B[0][3]
D[11][9] = -B[1][3]
D[11][10] = -B[2][3]
D[11][11] = A[0][0] - B[3][3]

print(D)

F = np.zeros((12, 1))

F[3] = -A[0][3]
F[7] = -A[1][3]
F[11] = -A[2][3]

print(F)

[[ 0.27612546 -0.63081901 -0.2794155  -0.          2.          0.
   0.          0.          3.          0.          0.          0.        ]
 [-0.01563704  1.5469033  -0.9207306  -0.          0.          2.
   0.          0.          0.          3.          0.          0.        ]
 [ 0.6897544  -0.67086267  0.727636    0.          0.          0.
   2.          0.          0.          0.          3.          0.        ]
 [-1.         -2.         -3.          0.          0.          0.
   0.          2.          0.          0.          0.          3.        ]
 [ 5.          0.          0.          0.          5.27612546 -0.63081901
  -0.2794155  -0.          7.          0.          0.          0.        ]
 [ 0.          5.          0.          0.         -0.01563704  6.5469033
  -0.9207306  -0.          0.          7.          0.          0.        ]
 [ 0.          0.          5.          0.          0.6897544  -0.67086267
   5.727636   -0.          0.          0.          7.          0.

In [18]:
X = np.linalg.solve(D, F)
print(X)

[[ 9.47881565e-18]
 [ 1.74196595e-16]
 [-2.19677518e-16]
 [ 3.68794326e-01]
 [-1.34480936e-16]
 [ 2.10804263e-16]
 [ 1.65095925e-16]
 [-1.53191489e+00]
 [ 1.04949917e-16]
 [-3.13430585e-16]
 [ 5.97549646e-17]
 [-3.12056738e-01]]


In [22]:
Result = np.zeros((4, 4))

k = 0

for i in range(4):
    for j in range(4):
        if(k <=11):
            Result[i][j] = X[k]
        k = k + 1
        
Result[3][3] = 1
print(Result)

[[ 9.47881565e-18  1.74196595e-16 -2.19677518e-16  3.68794326e-01]
 [-1.34480936e-16  2.10804263e-16  1.65095925e-16 -1.53191489e+00]
 [ 1.04949917e-16 -3.13430585e-16  5.97549646e-17 -3.12056738e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
